version: '2'

services:

  dpi-api:
    build:
      context: ./api
    container_name: dpi-api
    environment: 
      - HOST_DATA_FOLDER=$HOST_DATA_FOLDER
      
      - NODE_ENV=$NODE_ENV

      - HTTP_HOST=$HTTP_HOST
      - HTTP_PORT=$HTTP_PORT
      - HTTP_SECURED=$HTTP_SECURED
      - HTTP_BASE_URL=$HTTP_BASE_URL
      
      - IMG_NAME=$IMG_NAME
      - KEYBOARD_LAYOUT=$KEYBOARD_LAYOUT
      - KEYBOARD_KEYMAP=$KEYBOARD_KEYMAP
      - TIMEZONE_DEFAULT=$TIMEZONE_DEFAULT
      - ENABLE_SSH=$ENABLE_SSH
      - LOCALE_DEFAULT=$LOCALE_DEFAULT
    
    volumes:
      - $HOST_DATA_FOLDER:$HOST_DATA_FOLDER
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - $HTTP_PORT:$HTTP_PORT
    depends_on: 
      - apt-cacher-ng
  
  apt-cacher-ng:
    container_name: apt-cacher-ng
    restart: unless-stopped
    image: r1cebank/apt-cacher-ng:latest
    ports:
    - "3142:3142"
    volumes:
    - $HOST_DATA_FOLDER/apt-cacher-ng:/var/cache/apt-cacher-ng

  dpi-builder:
    build:
      context: ./builder
      dockerfile: DockerfileBuilder
    container_name: dpi-builder
    environment: 
      - HOST_DATA_FOLDER=$HOST_DATA_FOLDER
    volumes:
      - $HOST_DATA_FOLDER:$HOST_DATA_FOLDER
      - /var/run/docker.sock:/var/run/docker.sock

networks: 
  default:
      external:
        name: dcd-net